### PR TITLE
v2.0

### PR DESCRIPTION
**Pull request by pavel-kirienko**
Changes:

* Completely new spin up algorithm:
  * supports operation in closed loop mode from virtually zero speed (it is still based on the BEMF feedback);
  * more reliable and more robust against suboptimal configuration;
  * can pick up synchronization if the rotor is already rotating.
* Significantly more reliable operation during rapid acceleration and deceleration, especially at high advance angles.
* Fixed minor issues with the PWM driver.
* Fixed the ADC sampling sequence so that the BEMF signal conditioning circuits have sufficient time to stabilize before the voltages are sampled. This change required me to reduce the BEMF oversampling ratio from 4 to 2 samples per phase per PWM period.
* Fixed the logic of the ADC sampling point computation.
* Configuration parameter changes.
  * Default minimum stable voltage lowered from 3 V to 2.5 V.
  * Default dead time reduced from 700 ns to 600 ns.
  * Initial commutation period during spinup lowered from 200 ms to 100 ms.
  * Parameter for the final commutation period is gone, now it is considered equal to the maximum allowed commutation period.
  * PWM frequency range changed to 10...40 kHz.
* Dynamic blanking time during spinup.
* Zero advance angle during spinup, always.
* Raised the maximum RPM limit; for 14 pole motor the maximum is now 14285 mechanical RPM.

This release does not require any modifications to the hardware.

Paging @PierricG, @dimracer, @aperture-laboratories.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Prebuilt binaries are temporarily available at <https://files.zubax.com/products/io.px4.sapog/beta/>.

**Comment by pavel-kirienko** [comment]
Note that the binaries linked above are compiled in debug mode. These are compiled in release mode and therefore they are more suitable for flight testing: <https://files.zubax.com/products/io.px4.sapog/beta-release/>

**Comment by mhkabir** [comment]
> This release does not require any modifications to the hardware.

Hmm.

**Comment by pavel-kirienko** [comment]
@mhkabir hmm?

**Comment by pavel-kirienko** [comment]
Release binaries at https://files.zubax.com/products/io.px4.sapog/beta/ were updated.

**Comment by pavel-kirienko** [comment]
@PierricG @eyeam3 the latest release build is available at https://files.zubax.com/products/io.px4.sapog/. I intend to merge it tomorrow or the day after, unless you have any issues to report.

**Pull request merged**
