### PR TITLE
Convert filter(lambda) into a list comprehension

### LINKED ISSUE #38: Python 3 syntax error on filter(lambda (x, y): )
At least one Python 3 syntax error remains...
```
./tools/benchmark/make_plots.py:36:43: E999 SyntaxError: invalid syntax
        filt_with_indices = filter(lambda (index, value): keep_indices[index], enumerate(value))
                                          ^
```
Is there a test case around this code?

A simple fix would be to remove the parens around __(index, value)__ but that works sometimes and not others so a strong test case is needed.  In general, modern Python used list comprehensions instead of filter() and map() especially when used with lambdas.

https://docs.python.org/3/whatsnew/3.0.html#views-and-iterators-instead-of-lists

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #38  To get the tests to pass, you will need to update the link to https://github.com/UAVCAN/pyuavcan/pull/78

### CODE REVIEW

**Comment by cclauss** [comment]
To get the tests to pass, you will need to update the link to https://github.com/UAVCAN/pyuavcan/pull/78

**Comment by cclauss** [comment]
> The code will break in Python 3 because the output of map() is an iterable

LOL...  You will never get that far on Python 3 because the lambdas inside the filter and inside the map are both Syntax Errors on Python 3.  I guess this is dead code that should be eliminated.

**Comment by pavel-kirienko** [comment]
My point is that this changeset is incomplete because it doesn't make the code compatible with Python 3, so it should be either updated further or not accepted at all. I think the latter is preferable because this toolset is actually no longer used.

**Comment by cclauss** [comment]
Ahh...  Now I understand your point about `keep_indices[i]`.  Let's leave the unused code as it is.

**Pull request closed without merging**
